### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by hyperclock** [henry-richard7/IPTV-Link-Scraper#1]
I tested this and this is what I got as a response:

```
  File "./IPTV-Scraper.py", line 16
    m3u_creator = open(f"{x.strftime('%d-%m-%y_%I-%M-%S %p')} IPTV.m3u8", "a", encoding="utf-8")
                                                                       ^
SyntaxError: invalid syntax
```

**Comment by henry-richard7** [comment]
what version of python your using?

**Comment by hyperclock** [comment]
I have 2 and 3 setup on Debian 10

**Comment by henry-richard7** [comment]
Use it in python 3

**Comment by illwill239** [comment]
Works perfectly for me :) thanks for making it! is there a way to make this work for different sites?

**Comment by henry-richard7** [comment]
Well this script is designed for https://streamtest.in/ site but you could use beautifulsoup4 python library to scrape from other sites
